name: Format

on: [push,pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_fmt_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: cargo fmt --check --verbose
